var mockData = 
[
    {
        "id": 29878196,
        "user": "'Cyrus Hilll'",
        "initials_background": "'#D86441'",
        "location": "'South Jadonville'",
        "vip": false,
        "total_reviews": 16,
        "user_id": 2640235,
        "review": "'Quia et et sit pariatur corrupti quo fugit. Vel quod molestias error laboriosam. Deserunt placeat autem et facilis voluptas incidunt. Ut tempore et alias ducimus repellendus. Et sunt voluptate.'",
        "overall": 1.75,
        "food": 1,
        "service": 2,
        "ambience": 2,
        "value": 2,
        "noise": "Energetic",
        "would_recommend": true,
        "date": "'Fri Feb 22 2019 09:33:34 GMT-0800 (PST)'",
        "restaurant_id": 39
    },
    {
        "id": 31467647,
        "user": "'Rachelle'",
        "initials_background": "'#D86441'",
        "location": "'South Mortimer'",
        "vip": false,
        "total_reviews": 22,
        "user_id": 3855699,
        "review": "'Repellendus dolorem sit mollitia hic expedita. Autem dolorem explicabo minima. Nostrum est tenetur dolorum. Dolores fugit nihil id consectetur in ut dolor est ab. Dolorum aspernatur illum deleniti natus autem illo magni.'",
        "overall": 4.75,
        "food": 4,
        "service": 5,
        "ambience": 5,
        "value": 5,
        "noise": "Energetic",
        "would_recommend": true,
        "date": "'Tue Sep 17 2019 20:42:45 GMT-0700 (PDT)'",
        "restaurant_id": 39
    },
    {
        "id": 40628839,
        "user": "'Gussie Feil'",
        "initials_background": "'#BB6ACD'",
        "location": "'Port Randi'",
        "vip": true,
        "total_reviews": 25,
        "user_id": 3615191,
        "review": "'Neque ut accusantium et et quasi vitae. Et quos quam ut. Quo quia in. Fuga rerum debitis cumque accusamus.'",
        "overall": 1.75,
        "food": 1,
        "service": 2,
        "ambience": 2,
        "value": 2,
        "noise": "Energetic",
        "would_recommend": false,
        "date": "'Sat Oct 06 2018 12:33:34 GMT-0700 (PDT)'",
        "restaurant_id": 39
    },
    {
        "id": 42570538,
        "user": "'Angelica Wisozk'",
        "initials_background": "'#D86441'",
        "location": "'O'Connerville'",
        "vip": false,
        "total_reviews": 18,
        "user_id": 5452624,
        "review": "'Quia velit similique corporis. Consequatur perferendis pariatur deserunt ducimus. Aut totam a minus illum voluptas sit et reiciendis. Beatae architecto tempore rerum aperiam quo. Corrupti neque fugit eius. Sit sed beatae facere fugiat pariatur itaque minima.'",
        "overall": 5,
        "food": 5,
        "service": 5,
        "ambience": 5,
        "value": 5,
        "noise": "Quiet",
        "would_recommend": true,
        "date": "'Sun Nov 11 2018 00:41:37 GMT-0800 (PST)'",
        "restaurant_id": 39
    },
    {
        "id": 42783853,
        "user": "'Drew'",
        "initials_background": "'#D86441'",
        "location": "'Jeromytown'",
        "vip": false,
        "total_reviews": 7,
        "user_id": 4666814,
        "review": "'Corporis reiciendis culpa saepe voluptas. Impedit rerum deserunt. Repellendus distinctio nesciunt voluptate nisi. Tempora alias eius necessitatibus odit nesciunt ab et sunt. Quam aut voluptate magnam. Quia sed aut quam eos aut nam sapiente eum.'",
        "overall": 4,
        "food": 3,
        "service": 3,
        "ambience": 5,
        "value": 5,
        "noise": "Moderate",
        "would_recommend": true,
        "date": "'Fri Dec 07 2018 12:15:10 GMT-0800 (PST)'",
        "restaurant_id": 39
    },
    {
        "id": 44043162,
        "user": "'Gerard'",
        "initials_background": "'#DF4E96'",
        "location": "'North Dandrefort'",
        "vip": false,
        "total_reviews": 19,
        "user_id": 3065722,
        "review": "'Sit ad quas voluptatibus incidunt ut. Animi voluptatem esse hic laudantium adipisci temporibus praesentium consequatur. In consectetur temporibus et minus sint voluptates quasi laborum. Et nihil animi perspiciatis perferendis amet sit ducimus commodi ut. Dignissimos delectus magnam perferendis.'",
        "overall": 4.5,
        "food": 5,
        "service": 4,
        "ambience": 4,
        "value": 5,
        "noise": "Quiet",
        "would_recommend": true,
        "date": "'Thu Nov 22 2018 15:58:10 GMT-0800 (PST)'",
        "restaurant_id": 39
    },
    {
        "id": 48559086,
        "user": "'Murray Friesen'",
        "initials_background": "'#DF4E96'",
        "location": "'Murazikchester'",
        "vip": true,
        "total_reviews": 4,
        "user_id": 1748661,
        "review": "'Sit enim dolore. Repellat saepe molestiae qui voluptatem dolor. Ea modi dolores. Et officiis officia amet odit quia reiciendis quasi tempore. Alias laboriosam eum molestiae rerum sunt enim nam assumenda.'",
        "overall": 2.75,
        "food": 2,
        "service": 5,
        "ambience": 2,
        "value": 2,
        "noise": "Energetic",
        "would_recommend": true,
        "date": "'Tue Sep 17 2019 17:15:51 GMT-0700 (PDT)'",
        "restaurant_id": 39
    },
    {
        "id": 55803549,
        "user": "'Beau Orn'",
        "initials_background": "'#BB6ACD'",
        "location": "'Wisozkton'",
        "vip": true,
        "total_reviews": 24,
        "user_id": 6387271,
        "review": "'Nobis repudiandae ipsum. Asperiores ut et et sequi. Illo et tempora quisquam est voluptatibus et corrupti.'",
        "overall": 4.5,
        "food": 5,
        "service": 5,
        "ambience": 4,
        "value": 4,
        "noise": "Quiet",
        "would_recommend": true,
        "date": "'Tue Sep 17 2019 21:18:27 GMT-0700 (PDT)'",
        "restaurant_id": 39
    }
];

export default mockData;